# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
    ANDROID_SDK_LOC: C:\Android\android-sdk
    ANDROID_NDK_ROOT_LOC: C:\Android
    ANDROID_CMD_LOC: C:\projects\android-cmd

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe -y
  # JOELwindows7: Install the wget and stuffs
  - cinst wget -y # downloader
  - cinst butler -y # upload to itch io
  # - cinst zip -y # zip it
  # - cinst unzip -y # unzip it
  - cinst android-sdk -y
  - cinst android-ndk --version=16.2 -y # JOELwindows7: are you pecking serious? you don't have 15.3 15c?!?!? wtf?!??!
  - cinst adb -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # android things
  # - wget -O openJDK.msi https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_windows_hotspot_8u292b10.msi
  - wget -q -O android_ndk.zip https://dl.google.com/android/repository/android-ndk-r15c-windows-x86_64.zip?hl=fi
  - wget -q -O android_cmd.zip https://dl.google.com/android/repository/commandlinetools-win-7302050_latest.zip
  # - wget -O android_sdk.zip https://dl.google.com/android/repository/platform-tools-latest-windows.zip
  - wget -q -O android_build-tools.zip https://dl.google.com/android/repository/build-tools_r30.0.1-windows.zip
  - wget -q -O android_platforms.zip https://dl.google.com/android/repository/android-19_r04.zip
  - wget -q -O android_platform-tools.zip https://dl.google.com/android/repository/platform-tools_r31.0.2-windows.zip
  # - msiexec /i openJDK.msi INSTALLLEVEL=1 INSTALLDIR="c:\Program Files\AdoptOpenJDK\" /quiet
  - mkdir tempExtract\build-tools
  - unzip .\android_ndk.zip -d "%ANDROID_NDK_ROOT_LOC%"
  - unzip .\android_cmd.zip -d "%ANDROID_SDK_LOC%"
  - unzip .\android_build-tools.zip -d .\tempExtract\build-tools
  - unzip .\android_platforms.zip -d "%ANDROID_SDK_LOC%"
  - unzip -n .\android_platform-tools.zip -d "%ANDROID_SDK_LOC%" 
  - move .\tempExtract\build-tools\* "%ANDROID_SDK_LOC%\build-tools" -y
  # - unzip .\android_sdk.zip "%ANDROID_SDK_LOC%"
  # Install project dependencies
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel -y
  - haxelib run lime setup -y
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git extension-webm https://github.com/KadeDev/extension-webm
  # - C:\Android\android-sdk\cmdline-tools\bin\sdkmanager.bat "platform-tools" "platforms;android-19" "build-tools;31.0.0-rc5" --sdk_root="%ANDROID_SDK_LOC%"
  - haxelib run lime config ANDROID_SDK "%ANDROID_SDK_LOC%"
  - haxelib run lime config ANDROID_NDK_ROOT "%ANDROID_NDK_ROOT_LOC%\android-ndk-r15c"
  - haxelib run lime config ANDROID_SETUP true
  - haxelib run lime config JAVA_HOME C:\Program Files\Java\jdk1.8.0_211
  - haxelib run lime rebuild extension-webm android
  - haxelib install linc_luajit
  - haxelib install actuate
  # - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  # JOELwindows7: Android permissioner
  - haxelib install android6permissions
  # - haxelib install androidhx
  - haxelib list

# No tests idk lol
build_script:
  - dir
  # - haxelib run lime rebuild extension-webm windows
  - haxelib run lime build android

after_build:
  - dir
  # JOELwindows7: upload to itch
  # wtf, appveyor did not expect Git
  - butler push "C:\projects\kaded-fnf-mods-winDroid\export\release\android\bin\app\build\output\apk\Last Funkin Moments-debug.apk" joelwindows7/last-funkin-moments:android-appveyor

artifacts:
  - path: export\release\android\bin\app\build\output\apk\Last Funkin Moments-debug.apk
    name: last-funkin-moments-android
    # type: zip
  # - path: export/32bit/windows/bin
  #   name: last-funkin-moments-windows32
  #   type: zip
  # - path: export/release/html5/bin
  #   name: last-funkin-moments-html5
  #   type: zip
