version: '{build}'
image: macos
environment:
  global:
    HAXELIB_ROOT: /Users/appveyor/haxelib
    HAXE_INSTALLDIR: /Users/appveyor/haxe_bin

install:
  - cd /Users/appveyor
  - brew install neko
  - brew install gnu-tar
  - brew install wget
  # - brew install --cask butler # wait a minute. this isn't the butler we ask for
  # - brew install --cask itch
  - wget -q -O butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default
  - unzip ./butler.zip
  - wget "https://github.com/HaxeFoundation/haxe/releases/download/4.2.2/haxe-4.2.2-osx.tar.gz"
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.2.2-osx.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20210514141333_a2f4ba9
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel -y
  - haxelib run lime setup -y
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git extension-webm https://github.com/KadeDev/extension-webm
  - haxelib run lime rebuild extension-webm macos
  # - haxelib install linc_luajit
  - haxelib git linc_luajit https://github.com/JOELwindows7/linc_luajit.git # has Linux library finally
  - haxelib install actuate
  # - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  # JOELwindows7: Android permissioner
  - haxelib install android6permissions
  # - haxelib install androidhx
  - haxelib git haxe-hardware https://github.com/Perkedel/haxe-hardware.git
  - haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex # for the alternative against Lua, like BulbyVR's FNFM+
  - haxelib install tjson #BulbyVR used TJSON for JSON parsing instead of built-in JSON handlers.
  # - haxelib git haxevlc https://github.com/datee/HaxeVLC.git # for VLC.
  - haxelib list
  - pwd
  - cd /Users/appveyor/projects/kaded-fnf-mods-macos

build_script:
  # - haxelib run lime rebuild discord_rpc macos
  # - haxelib run lime rebuild extension-webm macos
  # - haxelib run lime rebuild linc_luajit macos # JOELwindows7: because it seems it only had windows?
  - haxelib run lime build macos

after_build:
  - hdiutil create /Users/appveyor/temp.dmg -ov -volname "last-funkin-moments-macOS" -fs HFS+ -srcfolder "/Users/appveyor/projects/kaded-fnf-mods-macos/export/release/macos/bin"
  - hdiutil convert /Users/appveyor/temp.dmg -format UDZO -o last-funkin-moments-macOS.dmg
  # JOELwindows7: upload to itch
  # - if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then butler push /Users/appveyor/last-funkin-moments-macOS.dmg joelwindows7/last-funkin-moments:macOS-appveyor; fi
  # wtf appveyor did not expect git
  - /Users/appveyor/butler push last-funkin-moments-macOS.dmg joelwindows7/last-funkin-moments:macOS-appveyor # stop being funny, mac! it's the command!!!

artifacts:
- path: last-funkin-moments-macOS.dmg
  name: Last Funkin Moments for macOS
